version: "3.3"
services:
  spark-master:
    hostname: spark-master
    container_name: spark-master
    image: cluster-apache-spark:3.5.3
    ports:
      - "9999:8080"
      - "7077:7077"
      - "4040:4040"
    volumes:
       - ./apps:/opt/spark-apps:z
       - ./data:/opt/spark-data:z
    env_file:
      - .env
    environment:
      - SPARK_LOCAL_IP=spark-master
      - SPARK_WORKLOAD=master
  spark-worker-0:
    hostname: spark-worker-0
    container_name: spark-worker-0
    image: cluster-apache-spark:3.5.3
    ports:
      - "9090:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=100G
      - SPARK_DRIVER_MEMORY=100G
      - SPARK_EXECUTOR_MEMORY=100G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-0
    volumes:
       - ./apps:/opt/spark-apps:z
       - ./data:/opt/spark-data:z
  spark-worker-1:
    hostname: spark-worker-1
    container_name: spark-worker-1
    image: cluster-apache-spark:3.5.3
    ports:
      - "9091:8080"
      - "7001:7000"
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=100G
      - SPARK_DRIVER_MEMORY=100G
      - SPARK_EXECUTOR_MEMORY=100G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-1
    volumes:
        - ./apps:/opt/spark-apps:z
        - ./data:/opt/spark-data:z
  spark-worker-2:
    hostname: spark-worker-2
    container_name: spark-worker-2
    image: cluster-apache-spark:3.5.3
    ports:
      - "9092:8080"
      - "7002:7000"
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=100G
      - SPARK_DRIVER_MEMORY=100G
      - SPARK_EXECUTOR_MEMORY=100G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-2
    volumes:
        - ./apps:/opt/spark-apps:z
        - ./data:/opt/spark-data:z
  spark-worker-3:
    hostname: spark-worker-3
    container_name: spark-worker-3
    image: cluster-apache-spark:3.5.3
    ports:
      - "9093:8080"
      - "7003:7000"
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=100G
      - SPARK_DRIVER_MEMORY=100G
      - SPARK_EXECUTOR_MEMORY=100G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-3
    volumes:
        - ./apps:/opt/spark-apps:z
        - ./data:/opt/spark-data:z
  spark-worker-4:
    hostname: spark-worker-4
    container_name: spark-worker-4
    image: cluster-apache-spark:3.5.3
    ports:
      - "9094:8080"
      - "7004:7000"
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=100G
      - SPARK_DRIVER_MEMORY=100G
      - SPARK_EXECUTOR_MEMORY=100G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-4
    volumes:
        - ./apps:/opt/spark-apps:z
        - ./data:/opt/spark-data:z
  spark-worker-5:
    hostname: spark-worker-5
    container_name: spark-worker-5
    image: cluster-apache-spark:3.5.3
    ports:
      - "9095:8080"
      - "7005:7000"
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=100G
      - SPARK_DRIVER_MEMORY=100G
      - SPARK_EXECUTOR_MEMORY=100G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-5
    volumes:
        - ./apps:/opt/spark-apps:z
        - ./data:/opt/spark-data:z
  spark-worker-6:
    hostname: spark-worker-6
    container_name: spark-worker-6
    image: cluster-apache-spark:3.5.3
    ports:
      - "9096:8080"
      - "7006:7000"
    depends_on:
      - spark-master
    env_file:
      - .env
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=100G
      - SPARK_DRIVER_MEMORY=100G
      - SPARK_EXECUTOR_MEMORY=100G
      - SPARK_WORKLOAD=worker
      - SPARK_LOCAL_IP=spark-worker-6
    volumes:
        - ./apps:/opt/spark-apps:z
        - ./data:/opt/spark-data:z
  minio:
    hostname: minio
    container_name: minio
    image: 'minio/minio:RELEASE.2024-01-13T07-53-03Z'
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio-data:/data:z
    environment:
      MINIO_ROOT_USER: accesskey
      MINIO_ROOT_PASSWORD: secretkey
    command: server /data --console-address ":9001"
#  demo-database:
#    image: postgres:11.7-alpine
#    ports: 
#      - "5432:5432"
#    environment: 
#      - POSTGRES_PASSWORD=casa1234
